# -*- coding: utf-8 -*-
"""carol

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bE4AlieDbCKGGmbBOF_j8dQK-fPjGQY6
"""

idioma = input("digite qual o idioma que você pretende estudar: ")
semana =  int (input("por quantas semanas você quer estudar: "))
matricula = 120
ingles = 200
frances = 170
alemao = 185


if (idioma == "inglês" ) or (idioma == "ingles"):
  pagamentoEscola = ingles*semana + matricula
  print("seu pagamento será de %0.2f"% pagamentoEscola, "reais.")
elif (idioma == "francês") or (idioma == "frances"):
  pagamentoEscola = frances*semana + matricula
  print("seu pagamento será de %0.2f"% pagamentoEscola, "reais.")
elif (idioma == "alemão") or (idioma == "alemao"):
  pagamentoEscola = frances*semana + matricula
  print("seu pagamento será de %0.2f"% pagamentoEscola, "reais.")
else:
  print("não temos esse idioma")