# -*- coding: utf-8 -*-
"""Código do açougue

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gI1p1ZbqUttUAFER64drcqlFp3bwzm10
"""

picanha = 40
maminha = 40
cupim = 30
costela = 30
outro = 25

tipoCarne= input("que tipo de carne você irá comprar? ")
kilo = float (input("quantos quilos? "))

if (tipoCarne.lower() == "picanha") or (tipoCarne.lower() == "maminha"):
  pagamento = picanha*kilo
  print ("sua compra irá custar : %0.2f"% pagamento, "reais")
elif (tipoCarne.lower() == "cupim") or (tipoCarne.lower() == "costela"):
  pagamento = cupim*kilo
  print ("sua compra irá custar : %0.2f"% pagamento, "reais")
  
else :
  pagamento = outro*kilo
  print ("sua compra irá custar : %0.2f"% pagamento, "reais")


if (pagamento > 50):
  print ("você ganhou 1 kg de linguiça")
else:
  print ("você não tem direito a ganhar a linguiça")