# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18bMhKtzW2pc5VcVq56pivCK03N_9PtkF
"""

bagagemLargura = float (input ("digite aqui a largura de sua bagagem: "))
bagagemComprimento = float(input("digite aqui o comprimento de sua bagagem: "))
bagagemAltura = float (input ("digite aqui a altura de sua bagagem: "))

if (bagagemLargura <=45) and (bagagemComprimento <=56) and (bagagemAltura<=25):
    print ("bagagem aceita!")
else:
    print ("bagagem não aceita, verifique as dimensões.")