# -*- coding: utf-8 -*-
"""helena cinema

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rok_RCXnnzPBYHjPEJGbiTcZwWbWzzU5
"""

duasDimensoes = 10.50
tresDimensoes = 17.50
comboSimples = 17
comboCompleto = 22

tipoFilme = input ("qual o tipo de filme que você quer assistir? ")
if (tipoFilme == "2d" ) or (tipoFilme == "duas dimensões" ) :
    pagamentoFilme = duasDimensoes
elif (tipoFilme == "3d") or (tipoFilme == "três dimensões" ):
    pagamentoFilme = tresDimensoes
    
lanche = input ("você deseja comprar lanche? ")
if (lanche == "sim"):
  tipoLanche = input ("digite qual o tipo de combo que você deseja: ")
  if (tipoLanche == "simples" ):
    pagamentoLanche = comboSimples
    pagamentoTotal = pagamentoLanche + pagamentoFilme
    print("sua compra custa",pagamentoTotal, "reais")   
  elif (tipoLanche == "completo"):
    pagamentoLanche = comboCompleto
    pagamentoTotal = pagamentoLanche + pagamentoFilme
    print("sua compra custa", pagamentoTotal, "reais") 
else:
    print("sua compra custa" ,pagamentoFilme, "reais")