# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zanczLz7UEomA0iTZtQ2TUjz_6dZVBYQ
"""

saborSorvete = input ("digite aqui qual o sabor do sorvete que você deseja: ")
bolasSorvete = int (input ("quantas bolas de sorvete voce deseja: "))

morango = 4.50
cereja = 4.50
damasco = 3.80
siriguela = 3.80
outro = 2.75

if (saborSorvete == "morango") or (saborSorvete == "cereja"):
    pagamento = morango*bolasSorvete
    print ("seu sorvete custa: %0.2f"% pagamento,"reais.")
elif (saborSorvete == "damasco") or (saborSorvete == "siriguela"):
    pagamento = damasco*bolasSorvete
    print("seu sorvete custa: %0.2f"% pagamento,"reais.")
else:
  pagamento = outro*bolasSorvete
  print ("seu sorvete custa: %0.2f"% pagamento,"reais.")
    
if (bolasSorvete >2):
    print ("você ganhou uma calda de caramelo!")
else:
    print ("você não ganhou calda.")